name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master-src

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Jekyll Action
        uses: helaili/jekyll-action@2.4.0
        env:
          JEKYLL_PAT: ${{ secrets.JEKYLL_PAT }}
